"""add trip days and special requests

Revision ID: 3a23d7f9b127
Revises: 61176aa585c9
Create Date: 2026-09-14 21:25:58.052554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a23d7f9b127'
down_revision: Union[str, None] = '61176aa585c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('days', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('special_requests', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'special_requests')
    op.drop_column('trips', 'days')
    # ### end Alembic commands ###
