"""add is_active to users and app_settings table

Revision ID: 3d29257e7458
Revises: 7e623aec6b19
Create Date: 2026-09-26 18:41:50.901822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d29257e7458'
down_revision: Union[str, None] = '7e623aec6b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # server_default backfills existing rows as active; dropped after so new rows rely on
    # the ORM default (models.User.is_active) rather than a permanent DB default.
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('users', 'is_active', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
