"""add platform and booking_url to itinerary items

Revision ID: 7e1e9adbbaf4
Revises: 3d29257e7458
Create Date: 2026-09-26 19:26:25.618211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e1e9adbbaf4'
down_revision: Union[str, None] = '3d29257e7458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_items', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('itinerary_items', sa.Column('booking_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_items', 'booking_url')
    op.drop_column('itinerary_items', 'platform')
    # ### end Alembic commands ###
