"""add is_template to trips

Revision ID: 7e623aec6b19
Revises: 3a23d7f9b127
Create Date: 2026-09-19 15:48:45.672264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e623aec6b19'
down_revision: Union[str, None] = '3a23d7f9b127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows as non-templates; dropped after so new rows
    # rely on the ORM default (models.Trip.is_template) rather than a permanent DB default.
    op.add_column('trips', sa.Column('is_template', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('trips', 'is_template', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_template')
    # ### end Alembic commands ###
